name: Build
on: [push]

jobs:
  linux:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install tools
        run: sudo apt-get -y install -y gcc make nasm

      - name: Build
        run: make os-image.bin
